services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_blog_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - sqlite_data:/var/www/html/var/data 
      - ./var/data/blog.sqlite:/var/www/html/var/data/blog.sqlite
      - ./var/data/blog.sqlite:/var/www/html/var/data/blog.sqlite
    environment:
      - APP_ENV=dev
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/blog.sqlite
      - COMPOSER_ALLOW_SUPERUSER=1
      - SYMFONY_ALLOW_ASSETS=1
    user: root
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/var &&
             chmod -R 777 /var/www/html/var &&
             apache2-foreground"
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: symfony_blog_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    restart: unless-stopped

  sqlitebrowser:
    image: linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
